"""create initial schema

Revision ID: 297e22f8a8fd
Revises: 
Create Date: 2026-08-13 13:12:52.355658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '297e22f8a8fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=64), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_gmail_message_id'), 'emails', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_emails_gmail_thread_id'), 'emails', ['gmail_thread_id'], unique=False)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_table('action_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('proposed_action', sa.Enum('categorize', 'move_to_trash', name='proposed_action'), nullable=False),
    sa.Column('category', sa.Enum('personal', 'trabajo', 'compras', 'banco', 'avisos', 'promociones', 'otros', name='category'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'modified', 'executed', 'failed', name='proposal_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_proposal_confidence_range'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_proposals_email_id'), 'action_proposals', ['email_id'], unique=False)
    op.create_index(op.f('ix_action_proposals_status'), 'action_proposals', ['status'], unique=False)
    op.create_index('uq_one_pending_proposal_per_email', 'action_proposals', ['email_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('personal', 'trabajo', 'compras', 'banco', 'avisos', 'promociones', 'otros', name='category'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_email_id'), 'classifications', ['email_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_proposal_id', sa.Integer(), nullable=True),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_proposal_id'), 'audit_logs', ['action_proposal_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_email_id'), 'audit_logs', ['email_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_email_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_proposal_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_classifications_email_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('uq_one_pending_proposal_per_email', table_name='action_proposals', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_action_proposals_status'), table_name='action_proposals')
    op.drop_index(op.f('ix_action_proposals_email_id'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_message_id'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
