"""track whether a decision was made blind

Añade `action_proposals.decidido_a_ciegas`.

NULLABLE A PROPÓSITO. Las filas que ya existían no saben si se decidieron
viendo la propuesta del modelo o no, y ese "no consta" hay que poder decirlo:
rellenarlas con `false` inventaría un dato, y con `true` mentiría a favor.
NULL las deja fuera de cualquier consulta de entrenamiento, que es lo correcto
—no son fiables— sin borrar la fila.


Revision ID: 3877d2e446c8
Revises: e2b5f8d41c77
Create Date: 2026-08-26 09:34:55.779693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3877d2e446c8'
down_revision: Union[str, Sequence[str], None] = 'e2b5f8d41c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_proposals', sa.Column('decidido_a_ciegas', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_proposals', 'decidido_a_ciegas')
    # ### end Alembic commands ###
