"""add final_category to action_proposals

Revision ID: 39fdf7424364
Revises: c2b681487998
Create Date: 2026-08-13 23:23:08.276095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '39fdf7424364'
down_revision: Union[str, Sequence[str], None] = 'c2b681487998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Añade final_category: la categoría que decide la usuaria.

    Corregido a mano respecto a lo que generó autogenerate. Alembic escribió
    sa.Enum(...), que intenta ejecutar CREATE TYPE category — y ese tipo ya
    existe desde la migración inicial, así que la migración reventaría.

    postgresql.ENUM con create_type=False reutiliza el tipo existente en vez
    de intentar crearlo. Es el motivo por el que conviene LEER siempre lo que
    genera autogenerate antes de aplicarlo.
    """
    op.add_column(
        "action_proposals",
        sa.Column(
            "final_category",
            postgresql.ENUM(name="category", create_type=False),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_proposals', 'final_category')
    # ### end Alembic commands ###
