"""add gmail_actions table

Revision ID: 976af0fe60a4
Revises: 39fdf7424364
Create Date: 2026-08-14 13:33:53.340021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '976af0fe60a4'
down_revision: Union[str, Sequence[str], None] = '39fdf7424364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('action_proposal_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('apply_label', 'move_to_trash', name='gmail_action_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'executed', 'failed', name='gmail_action_status'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_actions_action_proposal_id'), 'gmail_actions', ['action_proposal_id'], unique=False)
    op.create_index(op.f('ix_gmail_actions_email_id'), 'gmail_actions', ['email_id'], unique=False)
    op.create_index('uq_una_accion_pendiente_por_tipo', 'gmail_actions', ['email_id', 'action'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('uq_una_accion_pendiente_por_tipo', table_name='gmail_actions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_gmail_actions_email_id'), table_name='gmail_actions')
    op.drop_index(op.f('ix_gmail_actions_action_proposal_id'), table_name='gmail_actions')
    op.drop_table('gmail_actions')

    # Alembic no genera esto y es un fallo suyo conocido: en PostgreSQL los
    # ENUM son tipos independientes de la tabla, así que borrar la tabla los
    # deja huérfanos. Sin estos DROP TYPE, un `downgrade` seguido de `upgrade`
    # revienta con "type gmail_action_type already exists".
    sa.Enum(name='gmail_action_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='gmail_action_type').drop(op.get_bind(), checkfirst=True)
