"""track whether an email is in gmail trash

Revision ID: b5de04e85c16
Revises: 976af0fe60a4
Create Date: 2026-08-14 14:24:51.677661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5de04e85c16'
down_revision: Union[str, Sequence[str], None] = '976af0fe60a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('en_papelera', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('emails', sa.Column('sincronizado_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_emails_en_papelera'), 'emails', ['en_papelera'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_en_papelera'), table_name='emails')
    op.drop_column('emails', 'sincronizado_at')
    op.drop_column('emails', 'en_papelera')
    # ### end Alembic commands ###
