"""add retry counter to gmail actions

Revision ID: c6bfeb1778c7
Revises: c1a7de930b44
Create Date: 2026-08-14 18:47:39.953051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bfeb1778c7'
down_revision: Union[str, Sequence[str], None] = 'c1a7de930b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Contador de intentos por acción.

    `server_default='0'` NO es decorativo: sin él, añadir una columna
    `NOT NULL` a una tabla que ya tiene filas falla, porque PostgreSQL no sabe
    qué poner en las que existen. El defecto en Python (`default=0`) no sirve
    para esto: solo lo aplica SQLAlchemy al insertar, y aquí quien rellena las
    filas viejas es la base de datos.
    """
    op.add_column('gmail_actions', sa.Column('intentos', sa.Integer(), server_default=sa.text('0'), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gmail_actions', 'intentos')
    # ### end Alembic commands ###
